# Don't change this
configversion: 3

# Version of your plugin
version: 1

authors: # If you have a team of people that are working on this project
- tex

name: fcommands # The name must match the folder of the plugin

displayname: "Fuzzy-Commands" # This is just the displayname of your plugin

description: "A collection of commands that use the program `fzf` (fuzzy-finder)." # Description of your plugin

class: FCommands #This must match the class in the __init__.py class

dependencies:
- PyInputPlus