# Don't change this
configversion: 5

info:
  display_name: "Example Plugin"
  description: "Example"
  authors:
    - "Example"
  source_code_url: "https://github.com/example/exampleplugin"
  
config:
  name: "example_plugin"
  # The "name" field is case-sensitive and it NOT the display name.
  # The "name" field must be unique from other plugins

  version: "v1.0.0"
  # Must be v1.0.0 or b1.0.0 to allow version comparing

  class: "ExamplePlugin"
  # Must match the class in the plugin. This is where the plugin will be launched from.

  pip-dependencies:
  # This is for libraries and modules that are required for your plugin
  # - requests==2.23.2
  
  plugin-dependencies:
  # This is for plugins that your plugin depends on
  # - exampleplugin
